export const API_CONNECTION_STATUS = 'API_CONNECTION_STATUS';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const SET_ORDERS = 'SET_ORDERS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const POST_ORDER_SUCCEED = 'POST_ORDER_SUCCEED';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';

export const SET_ORDER_BY_ID = 'SET_ORDER_BY_ID';
export const FETCH_ORDER_BY_ID_FAILED = 'FETCH_ORDER_BY_ID_FAILED';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
